# Generated by Django 4.2.6 on 2023-10-09 17:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('escola', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='aluno',
            old_name='cof',
            new_name='cpf',
        ),
    ]
